### ISSUE TITLE
Gmail landscape mode issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#61] opened 2016-05-31 10:59 UTC
When our emails are viewed in landscape mode on gmail, the logo and the social media icons are not properly centered.

**Comment by cyrus-gc** [comment] 2016-06-06 06:57
Works as intended.
![gmail_landscape](https://cloud.githubusercontent.com/assets/12209741/15814130/08e245ca-2be2-11e6-990d-1b9b96a16033.png)

**Comment by mailanand75** [comment] 2016-06-06 12:23
Not fixed. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/12179089/15821790/9c1e00f4-2c0f-11e6-97ea-0ad377c6d4ec.png)

**Comment by cyrus-gc** [comment] 2016-09-08 10:04
Fixed. Please verify and close it.

**Closed as completed** 2016-09-08 10:28 UTC
