### ISSUE TITLE
Yahoo email not displaying Jodi Logik emails properly

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#60] opened 2016-05-31 10:45 UTC
Please check email formatting on Yahoo on mobile devices in portrait and landscape modes.

**Comment by cyrus-gc** [comment] 2016-06-06 06:56
Works as intended. Please attach the screenshots where you see the formatting issue.
![yahoo_email_1](https://cloud.githubusercontent.com/assets/12209741/15814096/c8481382-2be1-11e6-921f-ce06be30a082.png)
![yahoo_email_2](https://cloud.githubusercontent.com/assets/12209741/15814095/c8431e2c-2be1-11e6-9764-e61c77e80207.png)

**Comment by mailanand75** [comment] 2016-06-06 12:26
Not fixed. test this on mobile browser. here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/12179089/15821836/ed6af836-2c0f-11e6-9b00-604ec00ca64d.png)

**Comment by cyrus-gc** [comment] 2016-09-08 10:04
Fixed. Please verify and close it.

**Comment by mailanand75** [comment] 2016-09-08 10:26
The issue seems to be specific to the email sent when a new customer signs up (as shown in the screenshot above.) Please investigate.

**Comment by cyrus-gc** [comment] 2016-09-29 10:50
We have made the email content responsive. There is an Known Issue existing in Yahoo on Mobile browsers. If we change the Page Orientation after page load, the alignment problem will be occurred as mentioned in the screen shot.

**Closed as completed** 2016-09-30 12:03 UTC
